import*as THREE from"three";import{DoodleJoystick}from"./joystick.js";
const scene=new THREE.Scene();scene.background=new THREE.Color(0xc9edf5);scene.fog=new THREE.Fog(0xc9edf5,35,130);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,300),r=new THREE.WebGLRenderer({antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.setSize(innerWidth,innerHeight);r.shadowMap.enabled=true;document.body.appendChild(r.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x668060,2));let sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(20,40,20);sun.castShadow=true;scene.add(sun);
let ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0xa8d58e}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const mat=new THREE.MeshStandardMaterial({color:0xf1d49a});
function box(x,y,z,w,h,d,c=0xf1d49a){let m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:c}));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m)}
[[0,1,-12,12,1,9],[13,3,-23,10,1,8],[-12,5,-34,10,1,8],[4,7,-47,13,1,9],[18,10,-60,12,1,9],[0,13,-75,14,1,10]].forEach(a=>box(...a));
for(let i=0;i<45;i++){let g=new THREE.Group(),t=new THREE.Mesh(new THREE.CylinderGeometry(.3,.4,2.2,7),new THREE.MeshStandardMaterial({color:0x79533d})),c=new THREE.Mesh(new THREE.SphereGeometry(1.7,9,7),new THREE.MeshStandardMaterial({color:0x5fa95b}));t.position.y=1.1;c.position.y=3;g.add(t,c);g.position.set((Math.random()-.5)*165,0,(Math.random()-.5)*165);g.scale.setScalar(.7+Math.random()*.6);scene.add(g)}
function character(){let g=new THREE.Group(),b=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1,5,8),new THREE.MeshStandardMaterial({color:0xffcf4a})),h=new THREE.Mesh(new THREE.SphereGeometry(.55,12,9),new THREE.MeshStandardMaterial({color:0xffd5a0}));b.position.y=1.1;h.position.y=2.25;g.add(b,h);return g}const p=character();p.position.set(0,.2,8);scene.add(p);
const coins=[];for(let z of[0,-12,-23,-34,-47,-60,-75]){let q=new THREE.Mesh(new THREE.TorusGeometry(.35,.12,8,16),new THREE.MeshStandardMaterial({color:0xffcf27}));q.rotation.x=Math.PI/2;q.position.set(0,2+(z/-10),z);scene.add(q);coins.push(q)}
const joy=new DoodleJoystick("#joystick","#stick"),keys={};addEventListener("keydown",e=>keys[e.key.toLowerCase()]=1);addEventListener("keyup",e=>keys[e.key.toLowerCase()]=0);
let yaw=0,pitch=.35,drag=0,lx=0,ly=0;addEventListener("pointerdown",e=>{if(!e.target.closest("#joystick,button")){drag=1;lx=e.clientX;ly=e.clientY}});addEventListener("pointermove",e=>{if(drag){yaw-=(e.clientX-lx)*.006;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-ly)*.004,-.1,1);lx=e.clientX;ly=e.clientY}});addEventListener("pointerup",()=>drag=0);
let vy=0,grounded=false,dash=0,n=0,speed=0;function jump(){if(grounded){vy=8.5;grounded=false}}function doDash(){if(dash<=0){p.position.x+=Math.sin(yaw)*5;p.position.z+=Math.cos(yaw)*5;dash=.8}}
jumpBtn=document.querySelector("#jump");jumpBtn.onpointerdown=jump;document.querySelector("#dash").onpointerdown=doDash;
function update(dt){let x=joy.x,y=joy.y;if(keys.w)y--;if(keys.s)y++;if(keys.a)x--;if(keys.d)x++;let l=Math.hypot(x,y);if(l>1){x/=l;y/=l}let f=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),rt=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),d=new THREE.Vector3().addScaledVector(rt,x).addScaledVector(f,-y);if(d.length()>.08){d.normalize();speed=dash>0?15:7.5;p.position.addScaledVector(d,speed*dt);p.rotation.y=Math.atan2(d.x,d.z)}else speed=0;vy-=22*dt;p.position.y+=vy*dt;if(p.position.y<=.2){p.position.y=.2;vy=0;grounded=true}if(p.position.y<-8){p.position.set(0,.2,8);vy=0}dash=Math.max(0,dash-dt);for(let i=coins.length-1;i>=0;i--)if(p.position.distanceTo(coins[i].position)<1.5){scene.remove(coins[i]);coins.splice(i,1);n++}
let off=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch)*8.5,Math.sin(pitch)*8.5+3,Math.cos(yaw)*Math.cos(pitch)*8.5),want=p.position.clone().add(off);camera.position.lerp(want,1-Math.pow(.0005,dt));camera.lookAt(p.position.x,p.position.y+1.2,p.position.z);document.querySelector("#stats").textContent=`Speed ${speed.toFixed(1)} • Coins ${n}`}
let last=performance.now();function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);r.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();r.setSize(innerWidth,innerHeight)});